import { EndpointGroup } from '@/types/hr';

export const endpointGroups: EndpointGroup[] = [
  {
    id: 'attendance',
    label: 'Attendance',
    icon: 'event_available',
    requiredAnyPermissions: ['hr:attendance:read', 'hr:attendance:manage'],
    actions: [
      { title: 'Get Staff List', method: 'GET', path: '/hr/staff-list' },
      { title: 'Get Dashboard', method: 'GET', path: '/hr/dashboard' },
      { title: 'Get Attendance', method: 'GET', path: '/hr/attendance', query: ['date', 'month', 'staffId'] },
      { title: 'Monthly Attendance Report', method: 'GET', path: '/hr/attendance/monthly-report/:month', params: ['month'] },
      {
        title: 'Mark Attendance',
        method: 'POST',
        path: '/hr/attendance/mark',
        body: {
          staffId: '',
          date: '2026-05-01',
          status: 'PRESENT',
          checkIn: '09:10',
          checkOut: '17:40',
          punchMethod: 'MANUAL',
          workingHours: 8,
          remarks: '',
        },
      },
      {
        title: 'Bulk Mark Attendance',
        method: 'POST',
        path: '/hr/attendance/bulk-mark',
        body: {
          date: '2026-05-01',
          entries: [
            {
              staffId: '',
              status: 'PRESENT',
              checkIn: '09:00',
              checkOut: '17:30',
              punchMethod: 'BIOMETRIC',
              remarks: '',
            },
          ],
        },
      },
      {
        title: 'Update Attendance',
        method: 'PUT',
        path: '/hr/attendance/:id',
        params: ['id'],
        body: {
          status: 'HALF_DAY',
          checkIn: '10:00',
          checkOut: '14:30',
          punchMethod: 'MANUAL',
          workingHours: 4.5,
          remarks: '',
        },
      },
    ],
  },
  {
    id: 'leave',
    label: 'Leaves',
    icon: 'calendar_today',
    requiredAnyPermissions: ['hr:leave:read', 'hr:leave:manage', 'hr:leave:approve'],
    actions: [
      { title: 'Get Leave Types', method: 'GET', path: '/hr/leave/types' },
      {
        title: 'Create Leave Type',
        method: 'POST',
        path: '/hr/leave/types',
        body: { name: 'Special Casual Leave', code: 'SCL', maxPerYear: 3, carryForward: false },
      },
      { title: 'Get Leave Policy', method: 'GET', path: '/hr/leave/policy', query: ['staffId'] },
      { title: 'Get Leave Applications', method: 'GET', path: '/hr/leave/applications', query: ['status', 'staffId'] },
      {
        title: 'Apply Leave',
        method: 'POST',
        path: '/hr/leave/apply',
        body: {
          staffId: '',
          leaveTypeId: '',
          fromDate: '2026-05-10',
          toDate: '2026-05-12',
          days: 3,
          halfDay: false,
          reason: 'Medical leave',
        },
      },
      { title: 'Approve Leave', method: 'PUT', path: '/hr/leave/:id/approve', params: ['id'], body: { approvedBy: '' } },
      {
        title: 'Reject Leave',
        method: 'PUT',
        path: '/hr/leave/:id/reject',
        params: ['id'],
        body: { rejectedBy: '', rejectionNote: 'Insufficient balance' },
      },
      { title: 'Cancel Leave', method: 'PUT', path: '/hr/leave/:id/cancel', params: ['id'] },
      { title: 'Get Leave Balances', method: 'GET', path: '/hr/leave/balances', query: ['staffId', 'year'] },
      { title: 'Init Leave Balances', method: 'POST', path: '/hr/leave/balances/init', body: { staffId: '', year: '2026' } },
    ],
  },
  {
    id: 'permission',
    label: 'Permission',
    icon: 'schedule',
    requiredAnyPermissions: ['hr:permission:read', 'hr:permission:manage', 'hr:permission:approve'],
    actions: [
      { title: 'Get Permission Requests', method: 'GET', path: '/hr/permission', query: ['staffId', 'month', 'status'] },
      { title: 'Permission Summary', method: 'GET', path: '/hr/permission/summary/:month', params: ['month'] },
      {
        title: 'Apply Permission',
        method: 'POST',
        path: '/hr/permission/apply',
        body: { staffId: '', date: '2026-05-04', fromTime: '14:00', toTime: '16:00', hours: 2, reason: 'Personal work' },
      },
      { title: 'Approve Permission', method: 'PUT', path: '/hr/permission/:id/approve', params: ['id'], body: { approvedBy: '' } },
      {
        title: 'Reject Permission',
        method: 'PUT',
        path: '/hr/permission/:id/reject',
        params: ['id'],
        body: { rejectedBy: '', reason: 'Shift shortage', rejectionNote: 'Cannot spare staff this shift' },
      },
    ],
  },
  {
    id: 'payroll',
    label: 'Payroll',
    icon: 'payments',
    requiredAnyPermissions: ['hr:payroll:read', 'hr:payroll:manage', 'hr:payroll:approve'],
    actions: [
      { title: 'Generate Payroll', method: 'POST', path: '/hr/payroll/generate', body: { month: '2026-05', staffIds: [] } },
      { title: 'Get Payrolls', method: 'GET', path: '/hr/payroll', query: ['month', 'staffId', 'status'] },
      { title: 'Get Payroll Detail', method: 'GET', path: '/hr/payroll/:id', params: ['id'] },
      { title: 'Approve Payroll Batch', method: 'PUT', path: '/hr/payroll/approve', body: { ids: [] } },
      { title: 'Approve Payroll Row', method: 'PUT', path: '/hr/payroll/:id/approve', params: ['id'] },
      { title: 'LOP Report', method: 'GET', path: '/hr/payroll/lop-report/:month', params: ['month'] },
      {
        title: 'Update Payroll Manual',
        method: 'PUT',
        path: '/hr/payroll/:id/update',
        params: ['id'],
        body: { lopCancelled: false, bonusIncentive: 0, extraAllowance: 0 },
      },
      { title: 'Cancel Payroll LOP', method: 'PUT', path: '/hr/payroll/:id/cancel-lop', params: ['id'] },
      { title: 'Salary Abstract', method: 'GET', path: '/hr/salary-abstract/:month', params: ['month'] },
    ],
  },
  {
    id: 'statutory',
    label: 'PF / ESI',
    icon: 'account_balance',
    requiredAnyPermissions: ['hr:statutory:read', 'hr:statutory:manage', 'hr:payroll:read'],
    actions: [
      { title: 'Get Statutory Settings', method: 'GET', path: '/hr/statutory/settings' },
      {
        title: 'Update Statutory Settings',
        method: 'PUT',
        path: '/hr/statutory/settings',
        body: {
          pfEnabled: true,
          pfEmployeeRate: 12,
          pfEmployerRate: 12,
          pfWageLimit: 15000,
          pfAdminCharges: 0.5,
          pfEdliCharges: 0.5,
          esiEnabled: true,
          esiEmployeeRate: 0.75,
          esiEmployerRate: 3.25,
          esiWageLimit: 21000,
          esiDailyWageThreshold: 176,
          psfEnabled: false,
          psfEmployeeRate: 0,
          psfWageLimit: 0,
          ptEnabled: false,
          ptAmount: 0,
          basicRate: 50,
          hraRate: 20,
          travelAllowanceRate: 10,
          otherAllowanceRate: 20,
          clLapseMonths: 3,
        },
      },
      { title: 'Get Statutory Staff', method: 'GET', path: '/hr/statutory/staff' },
      {
        title: 'Update Staff Statutory',
        method: 'PUT',
        path: '/hr/statutory/staff/:staffId',
        params: ['staffId'],
        body: {
          pfNumber: '',
          uanNumber: '',
          esiNumber: '',
          basicSalary: 0,
          grossSalary: 0,
          pfEnabled: true,
          esiEnabled: true,
          psfEnabled: false,
          isStipend: false,
          dailyRate: 0,
        },
      },
      { title: 'Monthly Statutory Report', method: 'GET', path: '/hr/statutory/report/:month', params: ['month'] },
      { title: 'All Statutory Data', method: 'GET', path: '/hr/statutory/all' },
      { title: 'PF Staff Report', method: 'GET', path: '/hr/report/pf-staff', query: ['month'] },
      { title: 'Non-PF Staff Report', method: 'GET', path: '/hr/report/non-pf-staff', query: ['month'] },
    ],
  },
  {
    id: 'essl',
    label: 'ESSL',
    icon: 'fingerprint',
    requiredAnyPermissions: ['hr:essl:read', 'hr:essl:manage'],
    actions: [
      { title: 'Get Devices', method: 'GET', path: '/hr/essl/devices' },
      {
        title: 'Create Device',
        method: 'POST',
        path: '/hr/essl/devices',
        body: {
          name: 'Main Gate Reader',
          ipAddress: '192.168.1.20',
          port: 4370,
          serialNumber: 'SN123',
          deviceType: 'ZKTeco',
          location: 'Main Campus',
        },
      },
      {
        title: 'Update Device',
        method: 'PUT',
        path: '/hr/essl/devices/:id',
        params: ['id'],
        body: {
          name: 'Main Gate Reader',
          ipAddress: '192.168.1.20',
          port: 4370,
          serialNumber: 'SN123',
          deviceType: 'ZKTeco',
          location: 'Main Campus',
          isOnline: true,
        },
      },
      { title: 'Delete Device', method: 'DELETE', path: '/hr/essl/devices/:id', params: ['id'] },
      { title: 'Get Punch Logs', method: 'GET', path: '/hr/essl/punch-logs', query: ['deviceId', 'date', 'staffId'] },
      { title: 'Get Staff Mappings', method: 'GET', path: '/hr/essl/staff-mappings' },
      { title: 'Map Staff Device', method: 'POST', path: '/hr/essl/staff-mappings', body: { staffId: '', deviceId: '', deviceUserId: '' } },
      { title: 'Remove Staff Mapping', method: 'DELETE', path: '/hr/essl/staff-mappings/:staffId', params: ['staffId'] },
      { title: 'Sync Device', method: 'POST', path: '/hr/essl/sync/:deviceId', params: ['deviceId'] },
      { title: 'Sync All Devices', method: 'POST', path: '/hr/essl/sync-all' },
      { title: 'Sync History', method: 'GET', path: '/hr/essl/sync-history', query: ['deviceId'] },
    ],
  },
  {
    id: 'staff-finance',
    label: 'Staff & Finance',
    icon: 'groups',
    requiredAnyPermissions: ['hr:payroll:read', 'hr:payroll:manage', 'hr:payroll:approve'],
    actions: [
      { title: 'Create Advance Request', method: 'POST', path: '/hr/advance', body: { staffId: '', type: 'ADVANCE', amount: 5000, reason: '', monthlyDeduction: 1000 } },
      { title: 'Get Advance Requests', method: 'GET', path: '/hr/advance', query: ['staffId', 'status', 'type'] },
      { title: 'Get Advance Request', method: 'GET', path: '/hr/advance/:id', params: ['id'] },
      { title: 'Approve Advance', method: 'PUT', path: '/hr/advance/:id/approve', params: ['id'], body: { email: '' } },
      { title: 'Reject Advance', method: 'PUT', path: '/hr/advance/:id/reject', params: ['id'], body: { email: '', reason: 'Not eligible this month' } },
      { title: 'Disburse Advance', method: 'PUT', path: '/hr/advance/:id/disburse', params: ['id'] },
      {
        title: 'Create Increment',
        method: 'POST',
        path: '/hr/increment',
        body: {
          staffId: '',
          fromSalary: 30000,
          toSalary: 34000,
          incrementDate: '2026-05-01',
          effectiveDate: '2026-05-01',
          reason: 'Annual review',
        },
      },
      { title: 'Increment History', method: 'GET', path: '/hr/increment/history/:staffId', params: ['staffId'], query: ['status'] },
      { title: 'All Increments', method: 'GET', path: '/hr/increment/all', query: ['status'] },
      { title: 'Approve Increment', method: 'PUT', path: '/hr/increment/:id/approve', params: ['id'], body: { approvedBy: '', notes: '' } },
      { title: 'Reject Increment', method: 'PUT', path: '/hr/increment/:id/reject', params: ['id'], body: { rejectedBy: '', rejectionReason: 'Insufficient budget' } },
      {
        title: 'Create Loan',
        method: 'POST',
        path: '/hr/loan',
        body: {
          staffId: '',
          loanAmount: 50000,
          emiAmount: 5000,
          emiFrequency: 'MONTHLY',
          startMonth: '2026-06',
          reason: 'Personal',
        },
      },
      { title: 'Get Staff Loans', method: 'GET', path: '/hr/loan/staff/:staffId', params: ['staffId'], query: ['status'] },
      { title: 'Get Loan Detail', method: 'GET', path: '/hr/loan/:id', params: ['id'] },
      { title: 'Approve Loan', method: 'PUT', path: '/hr/loan/:id/approve', params: ['id'], body: { approvedBy: '', notes: '' } },
      { title: 'Reject Loan', method: 'PUT', path: '/hr/loan/:id/reject', params: ['id'], body: { rejectedBy: '', rejectionReason: 'Eligibility failed' } },
      { title: 'Skip EMI', method: 'PUT', path: '/hr/loan/:id/skip-emi', params: ['id'], body: { month: '2026-07', reason: '' } },
      { title: 'Resume EMI', method: 'PUT', path: '/hr/loan/:id/resume-emi', params: ['id'], body: { month: '2026-08' } },
      { title: 'Pre-close Loan', method: 'PUT', path: '/hr/loan/:id/pre-close', params: ['id'], body: { partialAmount: 10000, reason: '' } },
      { title: 'Loans by Status', method: 'GET', path: '/hr/loan-by-status/:status', params: ['status'] },
    ],
  },
];
